### ISSUE TITLE
提个小建议 —— cdn.jsdelivr.net 访问速度慢，或者超时

### ISSUE THREAD

**Issue by JoyWonderful** [wanzm1105/wanzm1105.github.io#1]
[cdn.jsdelivr.net](https://cdn.jsdelivr.net/) 在国内有时**无法快速或者正常访问**（被 DNS 污染了），而您的博客加载 font-awesome 图标时使用了 jsdelivr，有时可以在控制台看到 关闭连接/请求超时 的错误。

![fa-jsdelivr-timedout.png](https://s2.loli.net/2023/10/05/uYVoRmOQh1x9AUS.png)

建议您将所有引用了 cdn.jsdelivr.net 的地方改成其他 cdn（如 [cdnjs.cloudflare.com](https://cdnjs.cloudflare.com/)）

如果您懒得换，您可以忽略这个~~啸~~小建议，关掉这个 issue。  
谢谢！

**Comment by JoyWonderful** [comment]
https://github.com/wanzm1105/wanzm1105.github.io/blob/eaa4a166e0a10e12bc1511bd8ea9535e96169941/index.html#L41-L42

https://github.com/wanzm1105/wanzm1105.github.io/blob/eaa4a166e0a10e12bc1511bd8ea9535e96169941/index.html#L12

所有页面。

懒得提 PR 了。

**Comment by wanzm1105** [comment]
我没有想到有人给我发邮件，thankyou~
但是我纯纯小白，博客是照葫芦画瓢的qwq
请问你是通过什么途径知道我邮箱的？
加下联系方式，谢谢


| |
wanzm1105
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年10月5日 15:26 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> |
| 主题 | [wanzm1105/wanzm1105.github.io] 提个小建议 —— cdn.jsdelivr.net 访问速度慢，或者超时 (Issue #1) |

cdn.jsdelivr.net 在国内有时无法快速或者正常访问（被 DNS 污染了），而您的博客加载 font-awesome 图标时使用了 jsdelivr，有时可以在控制台看到 关闭连接/请求超时 的错误。

建议您将所有引用了 cdn.jsdelivr.net 的地方改成其他 cdn（如 cdnjs.cloudflare.com）

如果您懒得换，您可以忽略这个啸小建议，关掉这个 issue。
谢谢！

**Comment by wanzm1105** [comment]
JoyWonderful的小窝 - Be HardWorking Every Day.


我逐渐理解一切


| |
wanzm1105
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年10月5日 15:26 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> |
| 主题 | [wanzm1105/wanzm1105.github.io] 提个小建议 —— cdn.jsdelivr.net 访问速度慢，或者超时 (Issue #1) |

cdn.jsdelivr.net 在国内有时无法快速或者正常访问（被 DNS 污染了），而您的博客加载 font-awesome 图标时使用了 jsdelivr，有时可以在控制台看到 关闭连接/请求超时 的错误。

建议您将所有引用了 cdn.jsdelivr.net 的地方改成其他 cdn（如 cdnjs.cloudflare.com）

如果您懒得换，您可以忽略这个啸小建议，关掉这个 issue。
谢谢！

**Comment by JoyWonderful** [comment]
啊，我不知道你的邮箱，这是 github **自动**给你发的邮件，因为你 [watching](https://github.com/wanzm1105/wanzm1105.github.io/watchers) 了这个仓库（仓库所有者会接受关于这个仓库的一切信息），我只是提了个建议，我是在[这里](https://github.com/wanzm1105/wanzm1105.github.io/issues/1)\(#1\)提建议的。  
你可以看到这个邮件下方有这么一行小字：
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.

~~机器~~翻译过来就是：
> 直接回复此电子邮件，在 GitHub 上查看或取消订阅。
> 您收到此消息是因为您订阅了此线程。

联系方式嘛，[这个帖子](https://www.luogu.com.cn/discuss/647168 "求助万能谷友之搭建博客 - 洛谷 | 在洛谷，享受 WA 的快乐")你还记得吗，你看看一楼的头像（逃）

我不是什么大佬，这个小建议希望采纳！
